export const COMMON_TIMEZONES: Array<{ value: string; label: string }> = [
  { value: 'Pacific/Honolulu',        label: '(GMT-10:00) Hawaii' },
  { value: 'America/Anchorage',       label: '(GMT-09:00) Alaska' },
  { value: 'America/Los_Angeles',     label: '(GMT-08:00) Pacific Time (US & Canada)' },
  { value: 'America/Denver',          label: '(GMT-07:00) Mountain Time (US & Canada)' },
  { value: 'America/Phoenix',         label: '(GMT-07:00) Arizona' },
  { value: 'America/Chicago',         label: '(GMT-06:00) Central Time (US & Canada)' },
  { value: 'America/Mexico_City',     label: '(GMT-06:00) Mexico City' },
  { value: 'America/New_York',        label: '(GMT-05:00) Eastern Time (US & Canada)' },
  { value: 'America/Toronto',         label: '(GMT-05:00) Toronto' },
  { value: 'America/Bogota',          label: '(GMT-05:00) Bogota' },
  { value: 'America/Lima',            label: '(GMT-05:00) Lima' },
  { value: 'America/Halifax',         label: '(GMT-04:00) Atlantic Time (Canada)' },
  { value: 'America/Caracas',         label: '(GMT-04:00) Caracas' },
  { value: 'America/Santiago',        label: '(GMT-03:00) Santiago' },
  { value: 'America/Sao_Paulo',       label: '(GMT-03:00) Brasilia' },
  { value: 'America/Argentina/Buenos_Aires', label: '(GMT-03:00) Buenos Aires' },
  { value: 'Atlantic/Azores',         label: '(GMT-01:00) Azores' },
  { value: 'Atlantic/Cape_Verde',     label: '(GMT-01:00) Cape Verde' },
  { value: 'Europe/London',           label: '(GMT+00:00) London' },
  { value: 'Europe/Lisbon',           label: '(GMT+00:00) Lisbon' },
  { value: 'Africa/Casablanca',       label: '(GMT+00:00) Casablanca' },
  { value: 'Europe/Paris',            label: '(GMT+01:00) Paris' },
  { value: 'Europe/Berlin',           label: '(GMT+01:00) Berlin' },
  { value: 'Europe/Rome',             label: '(GMT+01:00) Rome' },
  { value: 'Europe/Madrid',           label: '(GMT+01:00) Madrid' },
  { value: 'Africa/Lagos',            label: '(GMT+01:00) Lagos' },
  { value: 'Europe/Athens',           label: '(GMT+02:00) Athens' },
  { value: 'Africa/Cairo',            label: '(GMT+02:00) Cairo' },
  { value: 'Africa/Johannesburg',     label: '(GMT+02:00) Johannesburg' },
  { value: 'Europe/Helsinki',         label: '(GMT+02:00) Helsinki' },
  { value: 'Europe/Istanbul',         label: '(GMT+03:00) Istanbul' },
  { value: 'Europe/Moscow',           label: '(GMT+03:00) Moscow' },
  { value: 'Asia/Baghdad',            label: '(GMT+03:00) Baghdad' },
  { value: 'Asia/Riyadh',             label: '(GMT+03:00) Riyadh' },
  { value: 'Africa/Nairobi',          label: '(GMT+03:00) Nairobi' },
  { value: 'Asia/Tehran',             label: '(GMT+03:30) Tehran' },
  { value: 'Asia/Dubai',              label: '(GMT+04:00) Dubai' },
  { value: 'Asia/Baku',               label: '(GMT+04:00) Baku' },
  { value: 'Asia/Kabul',              label: '(GMT+04:30) Kabul' },
  { value: 'Asia/Karachi',            label: '(GMT+05:00) Karachi' },
  { value: 'Asia/Tashkent',           label: '(GMT+05:00) Tashkent' },
  { value: 'Asia/Kolkata',            label: '(GMT+05:30) Mumbai, Kolkata, New Delhi' },
  { value: 'Asia/Colombo',            label: '(GMT+05:30) Sri Lanka' },
  { value: 'Asia/Kathmandu',          label: '(GMT+05:45) Kathmandu' },
  { value: 'Asia/Dhaka',              label: '(GMT+06:00) Dhaka' },
  { value: 'Asia/Almaty',             label: '(GMT+06:00) Almaty' },
  { value: 'Asia/Yangon',             label: '(GMT+06:30) Yangon' },
  { value: 'Asia/Bangkok',            label: '(GMT+07:00) Bangkok' },
  { value: 'Asia/Jakarta',            label: '(GMT+07:00) Jakarta' },
  { value: 'Asia/Ho_Chi_Minh',        label: '(GMT+07:00) Ho Chi Minh City' },
  { value: 'Asia/Shanghai',           label: '(GMT+08:00) Beijing, Shanghai' },
  { value: 'Asia/Hong_Kong',          label: '(GMT+08:00) Hong Kong' },
  { value: 'Asia/Singapore',          label: '(GMT+08:00) Singapore' },
  { value: 'Asia/Kuala_Lumpur',       label: '(GMT+08:00) Kuala Lumpur' },
  { value: 'Asia/Manila',             label: '(GMT+08:00) Manila' },
  { value: 'Asia/Taipei',             label: '(GMT+08:00) Taipei' },
  { value: 'Asia/Tokyo',              label: '(GMT+09:00) Tokyo, Osaka' },
  { value: 'Asia/Seoul',              label: '(GMT+09:00) Seoul' },
  { value: 'Australia/Darwin',        label: '(GMT+09:30) Darwin' },
  { value: 'Australia/Adelaide',      label: '(GMT+09:30) Adelaide' },
  { value: 'Australia/Sydney',        label: '(GMT+10:00) Sydney' },
  { value: 'Australia/Melbourne',     label: '(GMT+10:00) Melbourne' },
  { value: 'Australia/Brisbane',      label: '(GMT+10:00) Brisbane' },
  { value: 'Pacific/Auckland',        label: '(GMT+12:00) Auckland' },
  { value: 'Pacific/Fiji',            label: '(GMT+12:00) Fiji' },
];
